build:
    environment:
        php: '7.2'
        mysql: '5.7'
        hosts:
            laravel.dev: '127.0.0.1'
        variables:
            APP_KEY: 'base64:OYl4Bk9ekouOUIRXyeTD0FVi+cJ9D+HMyDJBgSBSUuI='
            APP_ENV: 'testing'
            APP_URL: 'http://laravel.dev'
            API_HOST: 'laravel.dev'
            DB_HOST: '127.0.0.1'
            DB_DATABASE: 'scrutinizer'
            DB_USERNAME: 'root'
            DB_PASSWORD: ''
            MAIL_DRIVER: 'log'
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - js-scrutinizer-run
                    -
                        command: eslint-run
                        use_website_config: false
            environment:
                node:
                    version: 8.11.1
        tests: true
filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
        - '*/vendor/*'
checks:
    php: true
    javascript: true
coding_style:
    php: {  }
