php:
  preset: laravel
  enabled:
    - alpha_ordered_imports
  disabled:
    - length_ordered_imports
    - unused_use
  finder:
    exclude:
      - "tests"
      - "node_modules"
      - "storage"
      - "vendor"
    not-name:
      - "AcceptanceTester.php"
      - "FunctionalTester.php"
      - "UnitTester.php"
      - index.php
      - server.php
