sudo: required
language: php
dist: trusty

php:
  - 7.3

addons:
  chrome: stable

install:
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction --prefer-dist --no-suggest
  - php artisan dusk:chrome-driver

before_script:
  - mysql -e 'create database testing;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &

script:
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - vendor/bin/phpunit
  - php artisan dusk
