language: php

php:
  - 7.1

before_script:
  - cp .env.testing .env
  - mysql -e 'create database testing;'
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan key:generate
  - vendor/bin/phpunit
